---
apiVersion: v1
kind: Pod
metadata:
  name: team22-pod
  labels:
    app: team22-pod
spec:
  containers:
  - name: backendserver
    image: ~/cs370TermProject1/BackendServer/backendserver:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 8000
  - name: clientserver
    image: ~/cs370TermProject1/ClientServer/clientserver:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: team22-service
  labels:
    app: team22-service
spec:
  type: NodePort
  selector:
    app: team22-pod
  ports:
  - name: http
    protocol: TCP
    targetPort: 9000
    port: 80
    nodePort: 30001